[build]
  base = "Frontend"              
  publish = "build"              
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.17.1"       

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
